trigger:
  branches:
    include:
      - '*'  # Triggers on all branches

steps:
  - checkout: self
  - script: |
      git config --global user.email "ghoshritaban2006@gmail.com"
      git config --global user.name "Ritaban Ghosh"
      git remote add azure https://dev.azure.com/vscode-ritaban/cloudflare-vercel-monitor/_git/cloudflare-vercel-monitor
      git fetch --unshallow
      git push --mirror azure  # Pushes all branches and tags
    displayName: 'Sync All Branches'
